"""
PDF export for research reports.

Uses reportlab to convert the structured ReportData into a clean,
readable PDF with a cover page and section bookmarks.

Install:  pip install reportlab
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app_agents.writer_agent import ReportData

try:
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        HRFlowable,
        PageBreak,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
    )
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False


def _clean(text: str) -> str:
    """Convert basic markdown to reportlab-compatible XML."""
    text = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"\*(.*?)\*", r"<i>\1</i>", text)
    text = re.sub(r"`(.*?)`", r"<font name='Courier'>\1</font>", text)
    text = re.sub(r"#{1,6}\s*", "", text)
    # Escape bare ampersands that aren't already entities
    text = re.sub(r"&(?!#?\w+;)", "&amp;", text)
    return text


def export_pdf(report: "ReportData", query: str, output_path: str | Path) -> Path:
    """
    Generate a PDF from a ReportData object and save it to output_path.
    Returns the resolved Path.

    Raises RuntimeError if reportlab is not installed.
    Install with:  pip install reportlab
    """
    if not REPORTLAB_AVAILABLE:
        raise RuntimeError(
            "reportlab is not installed. Run:  pip install reportlab"
        )

    output_path = Path(output_path)

    # ── Colour palette ─────────────────────────────────────────────────────
    NAVY       = colors.HexColor("#1a2a4a")
    TEAL       = colors.HexColor("#0f6e56")
    LIGHT_GRAY = colors.HexColor("#f5f5f5")
    MID_GRAY   = colors.HexColor("#cccccc")
    DARK_GRAY  = colors.HexColor("#444444")

    # ── Styles ─────────────────────────────────────────────────────────────
    base = getSampleStyleSheet()

    def add(name, **kw):
        base.add(ParagraphStyle(name=name, **kw))

    add("CoverTitle", fontSize=26, leading=32, textColor=NAVY,
        alignment=TA_CENTER, spaceAfter=8, fontName="Helvetica-Bold")
    add("CoverSub", fontSize=13, leading=18, textColor=DARK_GRAY,
        alignment=TA_CENTER, spaceAfter=4, fontName="Helvetica")
    add("SectionH", fontSize=14, leading=18, textColor=NAVY,
        spaceBefore=14, spaceAfter=4, fontName="Helvetica-Bold")
    add("BodyText2", fontSize=10, leading=15, textColor=DARK_GRAY,
        alignment=TA_JUSTIFY, spaceAfter=6, fontName="Helvetica")
    add("BulletItem", fontSize=10, leading=14, textColor=DARK_GRAY,
        leftIndent=12, spaceAfter=3, fontName="Helvetica", bulletIndent=4)
    add("SummaryBox", fontSize=10, leading=15, textColor=NAVY,
        backColor=LIGHT_GRAY, borderPadding=8, spaceAfter=10,
        fontName="Helvetica-Oblique")
    add("TOCItem", fontSize=10, leading=14, textColor=DARK_GRAY,
        leftIndent=8, fontName="Helvetica")
    add("KeyFact", fontSize=10, leading=14, textColor=DARK_GRAY,
        leftIndent=12, spaceAfter=2, fontName="Helvetica", bulletIndent=4)

    MARGIN = 20 * mm

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=MARGIN,
        bottomMargin=MARGIN,
        title=f"Research Report: {query[:80]}",
        author="Deep Research Agent",
    )

    story = []

    # ── Cover page ─────────────────────────────────────────────────────────
    story.append(Spacer(1, 30 * mm))
    story.append(Paragraph("Research Report", base["CoverTitle"]))
    story.append(HRFlowable(width="80%", color=TEAL, thickness=2, spaceAfter=8))
    story.append(Paragraph(_clean(query), base["CoverSub"]))
    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph("Generated by Deep Research Agent", base["CoverSub"]))
    story.append(PageBreak())

    # ── Executive summary ──────────────────────────────────────────────────
    story.append(Paragraph("Executive Summary", base["SectionH"]))
    story.append(HRFlowable(width="100%", color=MID_GRAY, thickness=0.5, spaceAfter=6))
    story.append(Paragraph(_clean(report.short_summary), base["SummaryBox"]))

    # ── Table of contents ──────────────────────────────────────────────────
    if report.table_of_contents:
        story.append(Spacer(1, 4 * mm))
        story.append(Paragraph("Contents", base["SectionH"]))
        story.append(HRFlowable(width="100%", color=MID_GRAY, thickness=0.5, spaceAfter=6))
        for i, title in enumerate(report.table_of_contents, 1):
            story.append(Paragraph(f"{i}.  {_clean(title)}", base["TOCItem"]))
        story.append(Spacer(1, 4 * mm))

    # ── Key facts ──────────────────────────────────────────────────────────
    if report.key_facts:
        story.append(PageBreak())
        story.append(Paragraph("Key Facts", base["SectionH"]))
        story.append(HRFlowable(width="100%", color=MID_GRAY, thickness=0.5, spaceAfter=6))
        for fact in report.key_facts:
            story.append(Paragraph(f"• {_clean(fact)}", base["KeyFact"]))
        story.append(Spacer(1, 4 * mm))

    # ── Body sections ──────────────────────────────────────────────────────
    for section in report.sections:
        story.append(PageBreak())
        story.append(Paragraph(_clean(section.title), base["SectionH"]))
        story.append(HRFlowable(width="100%", color=TEAL, thickness=1, spaceAfter=8))
        for para in section.content.split("\n\n"):
            para = para.strip()
            if not para:
                continue
            if para.startswith("- ") or para.startswith("* "):
                for line in para.splitlines():
                    line = re.sub(r"^[-*]\s+", "", line).strip()
                    if line:
                        story.append(Paragraph(f"• {_clean(line)}", base["BulletItem"]))
            else:
                story.append(Paragraph(_clean(para), base["BodyText2"]))

    # ── Contradictions ─────────────────────────────────────────────────────
    if report.contradictions_found:
        story.append(PageBreak())
        story.append(Paragraph("Contradictions & Caveats", base["SectionH"]))
        story.append(HRFlowable(width="100%", color=MID_GRAY, thickness=0.5, spaceAfter=6))
        for item in report.contradictions_found:
            story.append(Paragraph(f"• {_clean(item)}", base["BulletItem"]))

    # ── Follow-up questions ────────────────────────────────────────────────
    if report.follow_up_questions:
        story.append(Spacer(1, 6 * mm))
        story.append(Paragraph("Suggested Follow-up Questions", base["SectionH"]))
        story.append(HRFlowable(width="100%", color=MID_GRAY, thickness=0.5, spaceAfter=6))
        for q in report.follow_up_questions:
            story.append(Paragraph(f"• {_clean(q)}", base["BulletItem"]))

    doc.build(story)
    return output_path


def export_pdf_bytes(report: "ReportData", query: str) -> bytes:
    """
    Generate a PDF and return it as raw bytes (for download / email attachment).
    Does not write any file to disk.
    """
    import tempfile, os
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
        tmp_path = f.name
    try:
        export_pdf(report, query, tmp_path)
        with open(tmp_path, "rb") as f:
            return f.read()
    finally:
        os.unlink(tmp_path)